backend:
  name: github
  repo: tasty678/Winehero_Website
  branch: main
  auth_scope: repo


media_folder: "static/images/uploads"  # 上傳的圖片存放位置
public_folder: "/images/uploads"       # 圖片在網頁上的公開路徑

collections:
  - name: "products"
    label: "商品"
    folder: "content/products"
    create: true
    slug: "{{fields.slug}}"
    fields:
      - { label: "檔名path", name: "slug", widget: "string", required: true }
      - { label: "名稱", name: "name", widget: "string" }
      - { label: "英文名稱", name: "englisht_name", widget: "string" }
      - { label: "品牌", name: "brand", widget: "select", options: ["HB", "軒尼詩", "蘇格登","約翰走路","穆赫","皇家禮炮","馬爹利","歐肯特軒","亞柏樂","仕高利達"] }
      - { label: "描述", name: "description", widget: "text" }
      - { label: "價格", name: "price", widget: "number" }
      - { label: "圖片", name: "image", widget: "image" }
      - { label: "類別", name: "category", widget: "select", options: ["威士忌","啤酒","高粱","葡萄酒","伏特加","朗姆酒","琴酒","龍舌蘭","白蘭地","其他"] }
      - { label: "威士忌類別", name: "whiskey_type", widget: "select", options: ["單一麥芽威士忌", "調和威士忌", "波本威士忌","其他"] }
      - { label: "酒精濃度 %", name: "alcohol_content", widget: "number" }
      - { label: "產地", name: "origin", widget: "select", options: ["蘇格蘭", "美國", "法國","日本","英國","台灣","加拿大","其他"] }
      - { label: "年份", name: "year", widget: "number" }
      - { label: "容量 ml", name: "capacity", widget: "number" }
      - { label: "加入日期", name: "created_at", widget: "datetime" }
      
  - name: "news"  # 這是你的文章集合名稱，可以自定義
    label: "最新消息"  # 顯示在 CMS 的名稱
    folder: "content/news"  # 文章存放的資料夾
    create: true  # 允許在 CMS 中創建新的文章
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"  # 文章的 URL 結構
    fields:
      - { label: "標題", name: "title", widget: "string" }
      - { label: "發布日期", name: "date", widget: "datetime" }
      - { label: "內容", name: "body", widget: "markdown" }
      - { label: "圖片", name: "image", widget: "image" }
      - { label: "文章簡介", name: "excerpt", widget: "text" }


  
