backend:
  name: github
  repo: tasty678/Winehero_Website # Replace with your GitHub username and repo name

collections:
  - name: "products"
    label: "Products"
    folder: "content/products"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Product Name", name: "name", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Price", name: "price", widget: "number" }
      - { label: "Image", name: "image", widget: "image" }

    media_folder: "static/img"  # 上傳圖片的資料夾
    public_folder: "/img"      # 圖片在網頁上的公開路徑